 version: 2

 sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: pdt_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quanitity
             description: the quantity of products purchased for a given order

       - name: product
         identifier: raw_gz_product
         description: produst of Greenweez
         columns:
           - name: products_id
             description: Primary key
           - name: purchase_price
             description: the purchase price of the product

       - name: ship
         identifier: raw_gz_ship
         description: shipping data for Greenweez orders
         columns:
           - name: orders_id
             description: Primary key
           - name: shipping_fee
             description: the price the customer pays for shipping
           - name: log_cost
             description: the cost of preparing the parcel in the distribution centre/warehouse
           - name: ship_cost
             description: shipping cost paid by Greenweez to the carrier/logistics provider
    models:
      - name: int_sales_margin
        description: margin calcultation per order
        columns:
          - name: orders_id
            description: orders key
            tests:
              - not_null
          - name: products_id
            description: products key
            tests:
              - not_null
          - name: margin
            description: Margin = Revenue - Purchase_cost
            tests:
              - not_null
          - name: purchase_cost
            description: Purchase_cost = Quantity * Purchase_price
            tests:
              - not_null
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: revenue
            description: sum of revenue per order
            tests:
              - not_null
          - name: quantity
            description: sum of quantity per order
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(orders_id || '-' || products_id)"
